#!/bin/bash

printf "\n🚀  deploy\n"
printf "\n"
aws s3 cp \
  --delete \
  --recursive \
  --acl public-read \
  --region eu-central-1 \
  --exclude "assets/**.jpg" \
  --exclude "assets/**.png" \
  ./_site/ s3://christianfei.com
