#!/bin/bash

touch secrets
source secrets
printf "\n💥  purge cache for https://$CF_DOMAIN\n"
printf "\n"

curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE/purge_cache" \
     -H "Authorization: Bearer $CF_API_KEY" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}' --silent