#!/bin/bash

printf "\n📝  write\n"

args=$@
post_file_name_leading_dash=""

for arg in ${args[@]}; do
  post_file_name_leading_dash="$post_file_name_leading_dash-$arg"
done

post_file_name="$(date +%Y-%m-%d)$post_file_name_leading_dash.md"
post_full_path="posts/$post_file_name"

printf "\n> creating $post_full_path"

touch $post_full_path

date="$(date +%Y-%m-%d)"

touch $post_full_path
echo "---" >> $post_full_path
echo "title: $args" >> $post_full_path
echo "date: $date" >> $post_full_path
echo "layout: post.njk" >> $post_full_path
echo "tags:
  - post" >> $post_full_path
echo "---" >> $post_full_path
echo "" >> $post_full_path
vim $post_full_path
